
[workspace]
resolver = "2"
members = ["catsquad-api", "catsquad-client", "catsquad-db", "catsquad-log", "catsquad-web", "catsquad-shared"]
default-members = ["catsquad-api"]

[workspace.dependencies]
# api
axum = { version = "0.8.8", features = ["http1", "multipart", "form"] }
tokio = { version = "1.46.1" }
# tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread", "process", "fs"] }
http = "1.3.1"
tower = { version = "0.5.2" } # TODO make util testing only
tower-http = { version = "0.6.4", features = [
    "fs",
    # "compression-full",
    # "timeout",
    # "cors",
] }
#log
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
wasm-bindgen = { version = "0.2.122" }
#db
surrealdb = { git = "https://github.com/hey-adora/surrealdb", features = [
    "kv-surrealkv",
    "kv-mem",
] }
# web
strum = { version = "0.27.1", features = ["strum_macros", "derive"] }
leptos = { version = "0.8.17", features = ["csr"] }
leptos_router = { version = "0.8.12" }
console_error_panic_hook = "0.1.7"
hydration_context = { version = "0.3.0" }
# client
reqwest = { version = "0.13.2", features = ["zstd", "multipart", "stream", "json"] }
url = { version = "2.5.8" }

catsquad-log = { path = "catsquad-log" }
catsquad-db = { path = "catsquad-db" }
catsquad-api = { path = "catsquad-api" }
catsquad-shared = { path = "catsquad-shared" }
catsquad-client = { path = "catsquad-client" }
catsquad-web-utils = { path = "catsquad-web-utils" }

serde = { version = "1.0.219", features = ["serde_derive"] }
serde_urlencoded = "0.7.1"
serde_json = { version = "1.0.149" }
tokio-util = "0.7.18"
thiserror = { version = "2.0.12" }
rand = "0.9.1"

# chromiumoxide = "0.9.1"
leptos_axum = { version = "0.8.8" }
leptos_meta = { version = "0.8.6" }
# any_spawner = { version = "0.3.0" }
# little_exif = "0.6.14"
image = "0.25.6"
# webp = "0.3.0"
config = "0.15.14"
cfg-if = "1"
gxhash = { version = "3.5.0", features = ["deterministic"] }
argon2 = "0.5.3"
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
axum-test = { version = "19.0.0", features = ["reqwest", "typed-routing"] }
rkyv = { version = "0.8.10", features = ["unaligned"] }
server_fn = { version = "0.8.2", features = [] }
wasm-bindgen-futures = { version = "0.4.50" }
wasm-bindgen-test = "0.3.50"
send_wrapper = { version = "0.6.0" }
futures = { version = "0.3.31" }
futures-util = "0.3.32"
async-stream = "0.3.6"
bytes = "1.11.1"
anyhow = { version = "1.0.98" }
log = "0.4.27"
# js-sys = "0.3.99"
web-sys = { version = "0.3.91", features = [
    "Blob",
    "Crypto",
    "CssStyleDeclaration",
    "DataTransfer",
    "DomRect",
    "DomRectReadOnly",
    "DragEvent",
    "Element",
    "Event",
    "EventTarget",
    "File",
    "FileList",
    "FormData",
    "HtmlDivElement",
    "IntersectionObserver",
    "IntersectionObserverEntry",
    "IntersectionObserverInit",
    "Location",
    "MutationEvent",
    "MutationObserver",
    "MutationObserverInit",
    "MutationObserverInit",
    "MutationObservingInfo",
    "MutationRecord",
    "Node",
    "ProgressEvent",
    "ReadableStream",
    "ReadableStreamDefaultReader",
    "ReadableStreamReadResult",
    "ResizeObserver",
    "ResizeObserverEntry",
    "ResizeObserverSize",
    "ScrollBehavior",
    "ScrollIntoViewOptions",
    "ScrollLogicalPosition",
    "Window",
    "XmlHttpRequest",
    "XmlHttpRequestResponseType",
    "XmlHttpRequestUpload",
] }
