
[workspace]
resolver = "2"
members = ["artbounty", "artbounty-seed", "catsquad-api", "catsquad-client", "catsquad-db", "catsquad-log", "catsquad-web"]
default-members = ["catsquad-api"]

[workspace.dependencies]
# api
axum = { version = "0.8.8", features = ["http1", "multipart", "form"] }
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.5.2" } # TODO make util testing only
#log
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
wasm-bindgen = { version = "0.2.122" }
#db
surrealdb = { git = "https://github.com/hey-adora/surrealdb", features = [
    "kv-surrealkv",
    "kv-mem",
] }
# web
leptos = { version = "0.8.17", features = ["csr"] }
leptos_router = { version = "0.8.12" }
console_error_panic_hook = "0.1.7" # dyn

catsquad-log = { path = "catsquad-log" }
catsquad-db = { path = "catsquad-db" }

serde_json = { version = "1.0.149" }
tokio-util = "0.7.18"
thiserror = { version = "2.0.12" }
serde = { version = "1.0.219", features = ["serde_derive"] }
rand = "0.9.1"

# chromiumoxide = "0.9.1"
leptos_axum = { version = "0.8.8" }
leptos_meta = { version = "0.8.6" }
hydration_context = { version = "0.3.0" }
# any_spawner = { version = "0.3.0" }
strum = { version = "0.27.1", features = ["strum_macros", "derive"] }
artbounty = { path = "artbounty" }
# little_exif = "0.6.14"
image = "0.25.6"
# webp = "0.3.0"
config = "0.15.14"
cfg-if = "1"
gxhash = { version = "3.5.0", features = ["deterministic"] }
argon2 = "0.5.3"
reqwest = { version = "0.13.2", features = ["zstd", "multipart", "stream", "blocking"] }
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
axum-test = { version = "19.0.0", features = ["reqwest", "typed-routing"] }
http = "1.3.1"
tower-http = { version = "0.6.4", features = [
    "compression-full",
    "timeout",
    "cors",
] }
rkyv = { version = "0.8.10", features = ["unaligned"] }
server_fn = { version = "0.8.2", features = [] }
wasm-bindgen-futures = { version = "0.4.50" }
wasm-bindgen-test = "0.3.50"
send_wrapper = { version = "0.6.0" }
futures = { version = "0.3.31" }
futures-util = "0.3.32"
async-stream = "0.3.6"
bytes = "1.11.1"
anyhow = { version = "1.0.98" }
log = "0.4.27"
# js-sys = "0.3.99"
web-sys = { version = "0.3.91", features = [
    "Window",
    "HtmlDivElement",
    "Event",
    "EventTarget",
    "DataTransfer",
    "DragEvent",
    "Blob",
    "ReadableStream",
    "ReadableStreamDefaultReader",
    "ReadableStreamReadResult",
    "ResizeObserver",
    "ResizeObserverEntry",
    "Element",
    "Node",
    "ResizeObserverSize",
    "DomRectReadOnly",
    "DomRect",
    "MutationObserver",
    "MutationRecord",
    "MutationObservingInfo",
    "MutationEvent",
    "MutationObserverInit",
    "IntersectionObserver",
    "IntersectionObserverInit",
    "IntersectionObserverEntry",
    "MutationObserverInit",
    "Node",
    "File",
    "FileList",
    "XmlHttpRequest",
    "XmlHttpRequestUpload",
    # "Multipart",
    "Crypto",
    "CssStyleDeclaration",
    "ScrollIntoViewOptions",
    "ScrollBehavior",
    "ScrollLogicalPosition",
] }

[[workspace.metadata.leptos]]
name = "artbounty"
bin-package = "artbounty-backend"
lib-package = "artbounty-frontend"
output-name = "artbounty_1"
site-root = "target/site"
site-pkg-dir = "pkg"
tailwind-input-file = "style/tailwind.css"
assets-dir = "assets"
site-addr = "0.0.0.0:3000"
reload-port = 3001
end2end-cmd = "yarn playwright test"
end2end-dir = "e2e"
browserquery = "defaults"
watch = true
env = "DEV"
lib-profile-release = "wasm-release"
bin-features = []
lib-features = ["hydrate"]
bin-default-features = false
lib-default-features = false
