[package]
name = "catsquad-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_urlencoded = { workspace = true }
# reqwest = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
catsquad-log = { workspace = true }
strum = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
