[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=wild",
    # "-C",
    # "link-arg=-Wl,--no-rosegment",
    "-C",
    "target-feature=+aes,+sse2",
    # "-Z",
    # "share-generics=y",
    # "-Z",
    # "threads=4",
    "-C",
    "prefer-dynamic",
    "--cfg",
    "erase_components",
]
# rustflags = ["-C", "link-arg=-fuse-ld=mold", "-C", "target-feature=+aes,+sse2", "-Z", "share-generics=y", "--cfg", "erase_components"] +atomics

[target.wasm32-unknown-unknown]
# linker = "clang"
runner = 'wasm-bindgen-test-runner'
rustflags = [
    # "-Z",
    # "build-std",
    # "-Z",
    # "share-generics=y",
    # "-C",
    # "target-feature=+atomics,+bulk-memory,+mutable-globals",
    # "-C",
    # "link-args=--shared-memory",
    # "-C",
    # "link-args=--max-memory=1073741824",
    # "-C",
    # "link-args=--import-memory",
    # "-C",
    # "link-args=--export=__wasm_init_tls",
    # "-C",
    # "link-args=--export=__tls_size",
    # "-C",
    # "link-args=--export=__tls_align",
    # "-C",
    # "link-args=--export=__tls_base",
    "--cfg",
    "erase_components",

]
# rustflags = ["-C", "link-arg=-fuse-ld=mold", "-Z", "share-generics=y", "--cfg", "erase_components"]

# [unstable]
# codegen-backend = true

[profile.wasm_debug]
inherits = "dev"
incremental = true
opt-level = 0
lto = "off"
# codegen-backend = "llvm"
codegen-units = 256
panic = "abort"
debug = "none"
strip = "none"

[profile.wasm_debug.package."*"]
opt-level = 0
# codegen-backend = "llvm"

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 256
panic = "abort"

[profile.dev]
# codegen-backend = "cranelift"
opt-level = 0
incremental = true
codegen-units = 256
lto = "off"
debug = "none"
strip = "none"

[profile.dev.package."*"]
opt-level = "z"
# codegen-backend = "llvm"

[profile.dev.package.gxhash]
opt-level = "z"
# codegen-backend = "llvm"
