[package]
name = "catsquad-client"
version = "0.1.0"
edition = "2024"

[features]
xml_http_request = []
reqwest = [
    "dep:reqwest",
]
axum_test = [
    "dep:axum-test",
    "dep:tokio",
]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
catsquad-log = { workspace = true }
catsquad-shared = { workspace = true }
http = { workspace = true }
url = { workspace = true }
axum-test = { workspace = true, optional = true }
web-sys = { workspace = true }
reqwest = { workspace = true, optional = true }
tokio = { workspace = true, features = ["macros", "fs"], optional = true }
